id: DA5570577
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-18T11:12:56+00:00'
last_modified: '2022-05-27T15:40:24.137277+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    fee8:
      image_group_id: I1PD95909
      title: སྤྱོད་པ་བསྡུས་པའི་སྒྲོན་མ།
      total_pages: 1902
      order: 64
      base_file: fee8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
